services:
    app:
        container_name: "go-library-app"
        build:
            context: .
            dockerfile: dockerfile.dev # development dockerfile
        env_file: .env
        ports:
            - "${APP_PORT}:${APP_PORT}"
        volumes:
            - .:/app
            - go-mod-cache:/go/pkg/mod # module cache
            - go-build-cache:/root/.cache/go-build # build cache
        depends_on:
            - postgres

    postgres:
        container_name: "go-library-postgres"
        image: postgres:17-alpine
        environment:
            POSTGRES_USER: ${DB_USER}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_DB: ${DB_NAME}
        ports:
            - "${DB_PORT}:5432"
        volumes:
            - postgres-data:/var/lib/postgresql/data

    migrate:
        image: migrate/migrate
        volumes:
            - ./deploy/migrations:/migrations
        env_file: .env
        depends_on:
            - postgres
        entrypoint:
            - "migrate"
        command:
            - -path=/migrations
            - -database=postgres://${DB_USER}:${DB_PASSWORD}@postgres:5432/${DB_NAME}?sslmode=disable
            - up

volumes:
    postgres-data:
    go-mod-cache:
    go-build-cache:
